### ISSUE TITLE
ISO download location

### ISSUE THREAD

**Issue by drew9781** [chriswayg/packer-proxmox-templates#1]
First off, love this repo! 
So my question, why does the script download the ISO locally? Is this meant to be ran on the proxmox machine?

Because the image downloads locally, proxmox is unable to use it. Maybe I'm doing something wrong, who knows.

**Comment by chriswayg** [comment]
Hi @drew9781, I'm glad, that you like it. - Yes, this is meant to be run _on the Proxmox machine_, in a similar way that Packer scripts (templates) that create a Vagrant box are executed on the same machine where Virtualbox  and Vagrant is installed. If you prefer, you could run Proxmox locally (in a VM), then transfer the images using migration. - The build script downloads the ISO into the default directory used by Proxmox for starting VM installations. 

I added some text to emphasize the prerequisites in the read-me here:  
https://github.com/chriswayg/packer-proxmox-templates/blob/master/debian-10.0-x86_64-proxmox/README.md
